// packages/vue/src/studio/AiStudioProvider.tsx
import { defineComponent, provide, shallowRef, type PropType } from "vue";
import { createAiStudio, type AiStudio, type AiStudioConfig } from "@company/ai-composer-core";
import { AI_STUDIO_KEY } from "../composables/useAiStudio";

export interface AiStudioProviderProps {
  studio?: AiStudio;
  config?: AiStudioConfig;
}

export const AiStudioProvider = defineComponent({
  name: "AiStudioProvider",
  props: {
    studio: { type: Object as PropType<AiStudio>, default: undefined },
    config: { type: Object as PropType<AiStudioConfig>, default: undefined }
  },
  setup(props, { slots }) {
    const studio = shallowRef<AiStudio>(props.studio ?? createAiStudio(props.config));

    provide(AI_STUDIO_KEY, studio);

    return () => slots.default?.() ?? null;
  }
});

// packages/react/src/studio/AiStudioProvider.tsx
import { createContext, useContext, useState, type PropsWithChildren } from "react";
import { createAiStudio, type AiStudio, type AiStudioConfig } from "@company/ai-composer-core";

const AiStudioContext = createContext<AiStudio | null>(null);

export interface AiStudioProviderProps extends PropsWithChildren {
  studio?: AiStudio;
  config?: AiStudioConfig;
}

export function AiStudioProvider({ children, studio, config }: AiStudioProviderProps) {
  const [instance] = useState<AiStudio>(() => studio ?? createAiStudio(config));

  return <AiStudioContext.Provider value={instance}>{children}</AiStudioContext.Provider>;
}

export function useAiStudio(): AiStudio {
  const studio = useContext(AiStudioContext);

  if (!studio) {
    throw new Error("useAiStudio must be used inside AiStudioProvider.");
  }

  return studio;
}
